services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - WEBUI_AUTH=false
    volumes:
      - open-webui/data:/app/backend/data
    ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama/dot_ollama:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  youtube-knowledgebase:
    container_name: youtube-knowledgebase
    image: fastapi-youtube-knowledgebase:latest
    build:
      context: ./fastapi-youtube-kb
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-youtube-kb/data:/app/data
      - ./fastapi-youtube-kb/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  open-webui-data:
